package com.example.simplifiedcrm.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF1976D2)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFAFCAE6)
val light_onPrimaryContainer = Color(0xFF012B55)
val light_secondary = Color(0xFF566572)
val light_onSecondary = Color(0xFFA4A5A5)
val light_secondaryContainer = Color(0xFFE1EEFC)
val light_onSecondaryContainer = Color(0xFF004F9C)
val light_tertiary = Color(0xFF805B72)
val light_onTertiary = Color(0xFFFAEBEB)
val light_tertiaryContainer = Color(0xFFFCD3E9)
val light_onTertiaryContainer = Color(0xFF38152D)
val light_error = Color(0xFFBD1919)
val light_errorContainer = Color(0xFFFCD7D3)
val light_onError = Color(0xFFFFF6F6)
val light_onErrorContainer = Color(0xFF3C0002)
val light_background = Color(0xFFE0EFFF)
val light_onBackground = Color(0xFF292B2E)
val light_surface = Color(0xFFF5FAFF)
val light_onSurface = Color(0xFF1F2022)
val light_surfaceVariant = Color(0xFFD1D5DA)
val light_onSurfaceVariant = Color(0xFF4B5157)
val light_green = Color(0xFF65FA6C)

val dark_primary = Color(0xFF56A0E9)
val dark_onPrimary = Color(0xFF002242)
val dark_primaryContainer = Color(0xFF1E4469)
val dark_onPrimaryContainer = Color(0xFFD6E6F7)
val dark_secondary = Color(0xFFBBC6D1)
val dark_onSecondary = Color(0xFF2A353F)
val dark_secondaryContainer = Color(0xFF434D57)
val dark_onSecondaryContainer = Color(0xFFE2EEFA)
val dark_tertiary = Color(0xFFE6B7D2)
val dark_onTertiary = Color(0xFF442439)
val dark_tertiaryContainer = Color(0xFF58384C)
val dark_onTertiaryContainer = Color(0xFFFAD4E8)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF8B010A)
val dark_onError = Color(0xFF5E0005)
val dark_onErrorContainer = Color(0xFFFAD5D1)
val dark_background = Color(0xFF1C1E20)
val dark_onBackground = Color(0xFFDCDFE2)
val dark_surface = Color(0xFF1C1E20)
val dark_onSurface = Color(0xFFDEE0E2)
val dark_surfaceVariant = Color(0xFF414549)
val dark_onSurfaceVariant = Color(0xFFB9BFC5)
val dark_green = Color(0xFF59B35D)